apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "dbuser"
  POSTGRES_PASSWORD: "dbpass"
  POSTGRES_DB: "golemgrid"
