# Generated by Django 3.2.4 on 2021-06-15 20:39

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_file', models.FileField(max_length=150, upload_to='')),
                ('resolution', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None), size=None)),
                ('compositing', models.BooleanField()),
                ('crops', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('samples', models.PositiveIntegerField()),
                ('frames', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('output_format', models.CharField(max_length=6)),
                ('resources_dir', models.FilePathField()),
                ('work_dir', models.FilePathField()),
                ('output_dir', models.FilePathField()),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('Sent', 'Sent'), ('Computing', 'March'), ('Error', 'Error'), ('Finished', 'Finished')], default='Not Started', max_length=12)),
            ],
        ),
    ]
