# Generated by Django 3.2.9 on 2021-11-16 21:20

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlenderResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=api.models.blender_scene_path)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blender')),
            ],
        ),
    ]
