# Generated by Django 3.2.4 on 2021-06-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blender',
            name='compositing',
        ),
        migrations.RemoveField(
            model_name='blender',
            name='crops',
        ),
        migrations.RemoveField(
            model_name='blender',
            name='frames',
        ),
        migrations.RemoveField(
            model_name='blender',
            name='output_dir',
        ),
        migrations.RemoveField(
            model_name='blender',
            name='output_format',
        ),
        migrations.RemoveField(
            model_name='blender',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='blender',
            name='resources_dir',
        ),
        migrations.RemoveField(
            model_name='blender',
            name='samples',
        ),
        migrations.RemoveField(
            model_name='blender',
            name='scene_file',
        ),
        migrations.RemoveField(
            model_name='blender',
            name='work_dir',
        ),
        migrations.AddField(
            model_name='blender',
            name='task_args',
            field=models.JSONField(null=True),
        ),
    ]
