# Generated by Django 3.2.4 on 2021-06-20 07:20

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210616_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='blender',
            name='scene_file',
            field=models.FileField(default='/api-backend/media/scene.blend', upload_to=api.models.blender_scene_path),
            preserve_default=False,
        ),
    ]
