# Generated by Django 3.2.10 on 2021-12-23 13:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blenderresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blenderresult',
            name='file',
            field=models.FileField(upload_to=api.models.blender_output_path),
        ),
    ]
