# Generated by Django 3.2.4 on 2021-06-20 13:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blender_scene_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blender',
            name='scene_file',
            field=models.FileField(max_length=255, upload_to=api.models.blender_scene_path),
        ),
    ]
