# Generated by Django 3.2.4 on 2021-06-20 13:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blender_scene_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blender',
            name='scene_file',
            field=models.FileField(upload_to=api.models.blender_scene_path),
        ),
    ]
