# Generated by Django 3.2.8 on 2021-10-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_blender_scene_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blender',
            name='status',
            field=models.CharField(default='Not Started', max_length=12),
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=12, null=True)),
                ('provider', models.CharField(blank=True, max_length=42, null=True)),
                ('task_data', models.IntegerField()),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blender')),
            ],
        ),
    ]
