# Generated by Django 3.2.8 on 2021-10-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211006_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='provider_id',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
