#Location: .github/workflows/custom_config.yml

name: Build and push containers to Dockerhub
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

on:
  push:
    branches:
      - mono-repo #Use your own branch here (Might be staging or testing)
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Git clone on our repo
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Login to Dockerhub
        run: make login

      - name: Build Containers
        run: make build

      - name: Push to Dockerhub
        run: make push

      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.STAGING_HOST }}
            username: ${{ secrets.STAGING_USER }}
            key: ${{ secrets.STAGING_KEY }}
            port: ${{ secrets.STAGING_PORT }}
            script: |
                docker service update --force --image phillipjensen/golemgrid-backend:${{ github.sha }} golemgrid-backend_api
                docker service update --force --image phillipjensen/golemgrid-backend-celery:${{ github.sha }} golemgrid-backend_celery
                docker service update --force --image phillipjensen/golemgrid-backend-celery-beat:${{ github.sha }} golemgrid-backend_celery_beat
  
  